/**
 * Id skill/social khớp ICONS (+ phi-icon không có SVG).
 * Union compile-time — không import @portfolio/icons (content không phụ thuộc React).
 */
export const SKILL_IDS = [
  'javascript',
  'typescript',
  'html',
  'css',
  'scss',
  'python',
  'sql',
  'nosql',
  'react',
  'nextjs',
  'vuejs',
  'nuxt',
  'reactrouter',
  'nestjs',
  'tanstack',
  'zustand',
  'pinia',
  'reacthookform',
  'zod',
  'prisma',
  'tailwindcss',
  'shadcn',
  'radix',
  'antd',
  'bootstrap',
  'framermotion',
  'gsap',
  'threejs',
  'lighthouse',
  'wcag',
  'aria',
  'vitest',
  'testinglibrary',
  'playwright',
  'storybook',
  'cicd',
  'cursor',
  'claudecode',
  'git',
  'github',
  'nodejs',
  'expressjs',
  'django',
  'nitro',
  'mongodb',
  'postgres',
  'mysql',
  'redis',
  'websocket',
  'socketio',
  'jwt',
  'nx',
  'docker',
  'pnpm',
  'yarn',
  'vite',
  'postman',
  'vercel',
  'jira',
  'datadog',
  'sanity',
  'stripe',
  'facebook',
  'linkedin',
] as const

export type SkillId = (typeof SKILL_IDS)[number]

export const PHI_ICON_IDS = [
  'lighthouse',
  'wcag',
  'aria',
  'cicd',
  'testinglibrary',
  'jwt',
  'websocket',
  'cursor',
  'claudecode',
] as const satisfies readonly SkillId[]

export const PHI_ICON = new Set<string>(PHI_ICON_IDS)
