import type { ComponentType, SVGProps } from 'react'
import { LogoDark, LogoLight } from './brand'
import { Facebook, Github, Linkedin } from './social'
import {
  NextJs,
  Tailwind,
  Mongodb,
  TypeScript,
  CSS,
  GraphQL,
  HTML,
  JavaScript,
  Jira,
  NodeJs,
  Expressjs,
  NestJS,
  Postgres,
  Python,
  ReactIcon,
  Vuejs,
  Vercel,
  Vite,
  Yarn,
  Git,
  Prisma,
  ShadCn,
  AntDesign,
  Umami,
  BootStrap,
  Postman,
  SocketIO,
  DataDog,
  FramerMotion,
  MySQL,
  PNPM,
  ThreeJS,
  Nuxt,
  Pinia,
  Tanstack,
  Zustand,
  Zod,
  Radix,
  Gsap,
  Playwright,
  Vitest,
  Storybook,
  Nx,
  Docker,
  Redis,
  Django,
  Nitro,
  ReactRouter,
  ReactHookForm,
  Scss,
  Sql,
  Nosql,
  Sanity,
  Stripe,
} from './tech'

export const ICONS = {
  logodark: LogoDark,
  logolight: LogoLight,
  javascript: JavaScript,
  typescript: TypeScript,
  react: ReactIcon,
  vuejs: Vuejs,
  nextjs: NextJs,
  tailwindcss: Tailwind,
  bootstrap: BootStrap,
  shadcn: ShadCn,
  antd: AntDesign,
  css: CSS,
  html: HTML,
  graphql: GraphQL,
  prisma: Prisma,
  python: Python,
  nodejs: NodeJs,
  expressjs: Expressjs,
  nestjs: NestJS,
  git: Git,
  github: Github,
  facebook: Facebook,
  linkedin: Linkedin,
  mongodb: Mongodb,
  postgres: Postgres,
  mysql: MySQL,
  postman: Postman,
  vercel: Vercel,
  vite: Vite,
  threejs: ThreeJS,
  framermotion: FramerMotion,
  pnpm: PNPM,
  yarn: Yarn,
  jira: Jira,
  umami: Umami,
  datadog: DataDog,
  socketio: SocketIO,
  nuxt: Nuxt,
  pinia: Pinia,
  tanstack: Tanstack,
  zustand: Zustand,
  zod: Zod,
  radix: Radix,
  gsap: Gsap,
  playwright: Playwright,
  vitest: Vitest,
  storybook: Storybook,
  nx: Nx,
  docker: Docker,
  redis: Redis,
  django: Django,
  nitro: Nitro,
  reactrouter: ReactRouter,
  reacthookform: ReactHookForm,
  scss: Scss,
  sql: Sql,
  nosql: Nosql,
  sanity: Sanity,
  stripe: Stripe,
} as const satisfies Record<string, ComponentType<SVGProps<SVGSVGElement>>>

export type TypeOfIconsMap = keyof typeof ICONS
